-- CreateTable
CREATE TABLE "Sag" (
    "id" SERIAL NOT NULL,
    "typeid" INTEGER NOT NULL,
    "kategoriid" INTEGER NOT NULL,
    "statusid" INTEGER NOT NULL,
    "titel" TEXT NOT NULL,
    "titelkort" TEXT NOT NULL,
    "offentlighedskode" TEXT NOT NULL,
    "nummer" TEXT NOT NULL,
    "nummerprefix" TEXT NOT NULL,
    "nummernumerisk" TEXT NOT NULL,
    "nummerpostfix" TEXT,
    "resume" TEXT,
    "afstemningskonklusion" TEXT,
    "periodeid" INTEGER NOT NULL,
    "afgorelsesresultatkode" TEXT,
    "baggrundsmateriale" TEXT,
    "opdateringsdato" TIMESTAMP(3) NOT NULL,
    "statsbudgetsag" BOOLEAN NOT NULL,
    "begrundelse" TEXT,
    "paragrafnummer" INTEGER,
    "paragraf" TEXT,
    "afgorelsesdato" TIMESTAMP(3),
    "afgorelse" TEXT,
    "raadsmodedato" TIMESTAMP(3),
    "lovnummer" TEXT,
    "lovnummerdato" TIMESTAMP(3),
    "retsinformationsurl" TEXT,
    "fremsatundersagid" INTEGER,
    "deltundersagid" INTEGER,

    CONSTRAINT "Sag_pkey" PRIMARY KEY ("id")
);
